### ISSUE TITLE
How do you change the platform?

### ISSUE THREAD

**Issue by AwesomeKalin** [adamrehn/ue4-ci-helpers#1]
How do you change what platform is built for example, I want to build for Android? If it's not possible, please make it possible.

**Comment by adamrehn** [comment]
The `package()` method of the [PackagerBase](https://github.com/adamrehn/ue4-ci-helpers/blob/v0.0.11/ue4helpers/PackagerBase.py) class accepts a list of additional arguments to pass to the underlying [ue4 package](https://adamrehn.com/docs/ue4cli/descriptor-commands/package) command, which are in turn passed to UnrealAutomationTool, so you can specify the platform by simply providing the appropriate command-line flags:

```python
packager.package(args=['-platform=Android'])
```
